[package]
name = "bevy_urdf"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0"
bevy = { version = "0.15" }
rapier3d-urdf = {path="../rapier3d-urdf", features=["stl"] }
rapier3d = "0.23"
bevy_rapier3d = { version = "0.29", features = [ "simd-stable", "debug-render-3d" ] }
bevy_stl = "0.15"
rapier_testbed3d = "0.23.1"
urdf-rs = "0.9"
thiserror = "2.0"
bevy_flycam = "0.15.0"
bevy-inspector-egui = "0.30.0"